const fs = require("fs");
const path = require("path");

function parseEnv(content) {
  const env = {};
  content.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;
    const idx = trimmed.indexOf("=");
    if (idx === -1) return;
    const key = trimmed.slice(0, idx).trim();
    const val = trimmed.slice(idx + 1).trim().replace(/^['"]|['"]$/g, "");
    if (key) env[key] = val;
  });
  return env;
}

function loadApiUrl() {
  const envPath = path.join(__dirname, ".env");
  let apiUrl = process.env.API_URL;

  if (!apiUrl && fs.existsSync(envPath)) {
    const envVars = parseEnv(fs.readFileSync(envPath, "utf8"));
    apiUrl = envVars.API_URL;
  }

  if (!apiUrl) {
    throw new Error("API_URL is not set. Provide it via the environment or a .env file.");
  }

  return apiUrl.trim();
}

function writeConfig(apiUrl) {
  const dest = path.join(__dirname, "config.js");
  const banner = "// Generated by build-config.js; do not edit manually.\n";
  const body = `window.__API_URL__ = ${JSON.stringify(apiUrl)};\n`;
  fs.writeFileSync(dest, `${banner}${body}`, "utf8");
  console.log(`Wrote config.js with API_URL from environment.`);
}

function main() {
  try {
    const apiUrl = loadApiUrl();
    writeConfig(apiUrl);
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}

main();
